# Generated by Django 3.2.4 on 2021-06-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='año',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
