# Generated by Django 3.2.4 on 2021-06-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_artista_biografia_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Biografia',
        ),
        migrations.DeleteModel(
            name='Obra',
        ),
    ]
