# Generated by Django 3.2.4 on 2021-06-23 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_artista_biografia_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='num_id',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='id',
        ),
        migrations.AddField(
            model_name='artista',
            name='id_artista',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='Id Artista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='id_obra',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='Id Obra'),
            preserve_default=False,
        ),
    ]
