# Generated by Django 3.2.4 on 2021-06-23 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210622_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='id_obra',
        ),
        migrations.AddField(
            model_name='obra',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
