# Generated by Django 3.2.4 on 2021-06-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210623_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='num_id',
            new_name='id_artista',
        ),
    ]
