# Generated by Django 3.2.4 on 2021-06-23 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210622_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='id_artista',
            new_name='num_artista',
        ),
    ]
