# Generated by Django 3.2.4 on 2021-06-23 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_id_artista_artista_num_artista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='num_artista',
            new_name='id_artista',
        ),
    ]
