# Generated by Django 3.2.4 on 2021-06-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_biografia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biografia',
        ),
    ]
