# Generated by Django 3.2.4 on 2021-06-23 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_artista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biografia',
            fields=[
                ('id_bio', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Bio')),
                ('bio', models.TextField(max_length=150, verbose_name='Bio')),
                ('expos', models.TextField(max_length=150, verbose_name='Expos')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artista')),
            ],
        ),
    ]
