# Generated by Django 3.2.4 on 2021-06-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_artista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artista',
        ),
    ]
